### ISSUE TITLE
Unable to Update to Version 3.0.15

### ISSUE THREAD

**Issue by AbdullahSaad5** [Claxl/StickerBot#3]
I launched the index.js file and it told me that my version is outdated and had some 'Broken Methods'. So I stopped the execution and it showed me the command to use to update my version. `npm i @open-wa/wa-automate`. It finished updating. I ran the index.js file again and it tells me I'm still on the old version. Can't seem to figure it out. I don't know if its a bug or something. Please help me out. I will be thankful to you.
![Update Command](https://user-images.githubusercontent.com/56994371/99146598-70409880-269b-11eb-91a0-01c83f40c868.png)
![After Update](https://user-images.githubusercontent.com/56994371/99146609-85b5c280-269b-11eb-90d2-45d81416bb1c.png)

**Comment by Claxl** [comment]
Just try to unistall the library, because I've tried right now and there isn't broken method. If not work try to delete all folder and install all library a part

**Comment by AbdullahSaad5** [comment]
I've deleted the whole folder and did all the steps again but still couldn't get it to update. The bar progresses and shows that the version has been updated. After re-execution, it shows the same error again.
![Error](https://user-images.githubusercontent.com/56994371/99151576-1d2c0d00-26be-11eb-8fa8-985d1bd97c47.png)

**Comment by AbdullahSaad5** [comment]
Can you tell me how to uninstall library?

**Comment by Claxl** [comment]
npm unistall namePackage

**Comment by Claxl** [comment]
for example 
npm unistall @open-wa/wa-automate

**Comment by Claxl** [comment]
Just try to download package.json , I updated it. Now I'm working on notice that appear at launch but seems work fine

**Comment by AbdullahSaad5** [comment]
Yes it worked. The updated package.json file worked. Thank you so much.
