### ISSUE TITLE
How to stop the compression of Gifs

### ISSUE THREAD

**Issue by AbdullahSaad5** [Claxl/StickerBot#4]
When sending a gif/image to the bot that is rectangle. The gif gets compressed into a square which distorts the quality. When an image is sent to the bot, the image gets randomly cropped into a square and made into a sticker. Can you tell me how to fix this issue. A little help will be appreciated.

**Comment by Claxl** [comment]
It's not an issue. Is made in this way because is the only right now work in all platform. I'm working on to improve that. Right now is only with this method
